# 
---
- hosts: packstack
  become: true
  vars:
    my_auth:
      auth_url: https://{{ gather_facts.hostname }}
      username: admin
      password: admin
      project_name: admin
  tasks:

    - name: "Create 'tiny' flavor with 1024MB of RAM, 1 virtual CPU, and 10GB of local disk, and 10GB of ephemeral."
      openstack.cloud.compute_flavor:
        cloud: mycloud
        state: present
        name: tiny
        ram: 1024
        vcpus: 1
        disk: 10
        ephemeral: 10
        
    - name: create provider network
      openstack.cloud.network:
        auth: "{{my_auth}}"
        state: present
        provider_network_type: vlan
        provider_segmentation_id: 111
        provider_physical_network: physnet1
        external: True
        shared: True
        name: provider

    - name: Gather information about previously created networks
      openstack.cloud.networks_info:
        auth: my_auth
      register: result
    
    - name: Show openstack networks
      debug:
        msg: "{{ result.openstack_networks }}"
    
    - name: Gather information about a previously created network by name
      openstack.cloud.networks_info:
        auth:
          auth_url: https://identity.example.com
          username: user
          password: password
          project_name: someproject
        name:  provider
      register: provider_output
    
    - name: Create image cirros
      openstack.cloud.image:
        auth: "{{ my_auth }}"
        name: cirros
        container_format: bare
        disk_format: qcow2
        state: present
        filename: http://repo-1/images/cirros-0.3.0-x86_64-disk.img
        kernel: cirros-vmlinuz
        ramdisk: cirros-initrd
        tags:
          - custom
        properties:
          cpu_arch: x86_64
          distro: x64
    
    - name: launch a compute instance
      hosts: localhost
      tasks:
        - name: launch an instance
          openstack.cloud.server:
            state: present
            auth: "{{ vms_auth }}"
            name: vm1
            region_name: region-b.geo-1
            availability_zone: az2
            image: cirros
            network: provider
            key_name: test
            timeout: 200
            flavor: 101
            security_groups: 
              - default
              - allow_ssh_ping
            auto_ip: yes