---
- hosts: localhost
  vars_files: vars/vmw_env.yml
  gather_facts: no
  become: true
  fork: 6
  serial: 4
  tasks:     
    - name: Deploy the COA cluster on VMware environment
      include: deploy_vmware_coa_cluster.yml

- hosts: lab
  vars_files: vars/vmw_env.yml
  gather_facts: true
  become: true
  fork: 6
  serial: 4
  tasks: 
    - name: Prepare requirements on all node
      include: prepare_all_node.yml
  #- name: Preapre the storage on all node  
  #  include: prepare_storage_lvm.yml
    - name: Deploy the Openstack Xena by packstack on all host 
      include: deploy_packstack_openstack_xena.yml
    
- hosts: lab
  connection: local
  become: true
  vars_files: vars/os_env.yml
  vars:
    ansible_python_interpreter: /usr/bin/python3.8
  gather_facts: true
  tasks:  
    - name: Create a project for demo
      include: deploy_demo_project.yml
