---
- hosts: share
  vars_files: vars/vmw_env.yml
  gather_facts: true
  become: true
  serial: 4
  tasks: 
    - name: Prepare requirements on all node
      include: prepare_all_node.yml

    - name: Deploy the Openstack Xena by packstack on all host 
      include: deploy_packstack_openstack_xena.yml
    

