---
- name: "Create project flavor"
  openstack.cloud.compute_flavor:
    auth:
        auth_url: "http://{{ ansible_facts.default_ipv4.address }}:5000/v3"
        username: admin
        password: C0@lab!2022
        project_name: admin
        domain_id: default
    state: present
    name: "{{ item.name }}"
    ram: "{{ item.ram }}"
    vcpus: "{{ item.vcpus }}"
    disk: "{{ item.disk }}"
    ephemeral: "{{ item.ephemeral }}"
  loop: "{{ demo_flavors }}" 
    
- name: "Create project networks"
  openstack.cloud.network:
    auth:
        auth_url: "http://{{ ansible_facts.default_ipv4.address }}:5000/v3"
        username: admin
        password: C0@lab!2022
        project_name: admin
        domain_id: default
    state: present
    provider_network_type: "{{ item.provider_network_type }}"
    provider_segmentation_id: "{{ item.provider_segmentation_id }}"
    provider_physical_network: "{{ item.provider_physical_network }}"
    external: "{{ item.external }}"
    shared: "{{ item.shared }}"
    name: "{{ item.name }}"
  loop: "{{ demo_networks }}" 

- name: "Create project subnet"
  openstack.cloud.subnet:
    name: provider-flat-subnet
    auth:
        auth_url: "http://{{ ansible_facts.default_ipv4.address }}:5000/v3"
        username: admin
        password: C0@lab!2022
        project_name: admin
        domain_id: default
    state: present
    network_name: provider-flat
    cidr: 172.12.0.0/16
    dns_nameservers: 8.8.8.8
    ip_version: 4
    gateway_ip: 172.12.0.1
    allocation_pool_start: "{{ item.provider-subnet-start }}"
    allocation_pool_end: "{{ item.provider-subnet-end }}"
  loop: "{{ vms }}" 

- name: "Create project images"
  openstack.cloud.image:
    auth:
        auth_url: "http://{{ ansible_facts.default_ipv4.address }}:5000/v3"
        username: admin
        password: C0@lab!2022
        project_name: admin
        domain_id: default
    name: "{{ item.name }}"
    state: present
    container_format: "{{ item.container_format }}"
    disk_format: "{{ item.disk_format }}"
    filename: "{{ item.filename }}"
    kernel: "{{ item.kernel }}"
    ramdisk: "{{ item.ramdisk }}"
    properties:
      cpu_arch: "{{ item.properties.cpu_arch }}"
      distro: "{{ item.properties.distro }}"
  loop: "{{ demo_images }}" 
  
- name: "Create security groups"
  openstack.cloud.security_group:
    auth:
        auth_url: "http://{{ ansible_facts.default_ipv4.address }}:5000/v3"
        username: admin
        password: C0@lab!2022
        project_name: admin
        domain_id: default
    state: present
    name: "{{ item.name }}"
    description: "{{ item.description }}"
  loop: "{{ demo_security_groups }}" 

- name: "Create security group rules"
  openstack.cloud.security_group_rule:
    auth:
        auth_url: "http://{{ ansible_facts.default_ipv4.address }}:5000/v3"
        username: admin
        password: C0@lab!2022
        project_name: admin
        domain_id: default
    state: present
    security_group: "{{ item.security_group }}"
    protocol: "{{ item.protocol }}"
    port_range_min: "{{ item.port_range_min }}"
    port_range_max: "{{ item.port_range_max }}"
    remote_ip_prefix: "{{ item.remote_ip_prefix }}" 
    direction: "{{ item.direction }}" 
  loop: "{{ demo_security_group_rules }}" 

- name:  Creates a new instance and attaches to a specific network
  openstack.cloud.server:
    auth:
        auth_url: "http://{{ ansible_facts.default_ipv4.address }}:5000/v3"
        username: admin
        password: C0@lab!2022
        project_name: admin
        domain_id: default
    name: "{{ item.name }}" 
    state: present
    image: "{{ item.image }}" 
    flavor: "{{ item.flavor }}" 
    network: "{{ item.network }}" 
    security_groups: "{{ item.security_groups }}" 
  loop: "{{ demo_instances  }}" 